### ISSUE TITLE
t.component is not a function when using Tree View

### ISSUE THREAD

**Issue by mizzao** [michaelfitzhavey/vue-json-tree-view#21] opened 2017-12-21 16:41 UTC
When importing and using Tree View with Vue 2.5.11 I get the following error right off the bat:

![image](https://user-images.githubusercontent.com/2080084/34265246-609d9932-e643-11e7-8541-57bed1502f46.png)

It seems to come from this line of (minified, why? why?) JS:

```
t.exports=function(t){t.component("tree-view-item-value",i.default),t.component("tree-view-item",a.default),t.component("tree-view",c.default)}
```

..which seems to correspond to [this code](../blob/master/src/index.js). Any idea why this might be happening?

As an aside, I don't think that an NPM module should be published as minified JS. It makes debugging impossible, and most bundlers can do the minification afterward. Also it can introduce incompatibilities between different transpilers. #

**Comment by vxhly** [comment] 2018-01-04 03:34
you must installed 
```bash
import Vue from 'Vue'
import TreeView from 'vue-json-tree-view'
Vue.use(TreeView)
```
in your `main.js`

**Comment by proycon** [comment] 2018-05-19 15:10
I get the same error when I try to include it in my own Vue component:


```javascript
import Vue from 'vue'
import TreeView from 'vue-json-tree-view'

export default {
   components: {
      TreeView
  } 
}
```

**Comment by michaelfitzhavey** [comment] 2018-08-27 14:40
@proycon could you show an example of the vue component you are experiencing this issue in?

**Comment by proycon** [comment] 2018-08-28 12:33
Sorry, I'm no longer using this in my Vue component (this issue was a show-stopper), so I can't reproduce it currently.

**Comment by michaelfitzhavey** [comment] 2018-08-28 15:11
No worries, sorry to hear that. Hope you found something that works and I'll close this issue in a couple of days if it's still obsolete.

**Comment by ykl124** [comment] 2018-12-29 03:36
Global Registration：
`Vue.use(TreeView)`

Local Registration
`components: {
      'tree-view': TreeView
    },`

**Comment by tylerkrupicka** [comment] 2019-03-29 13:32
I made a package similar to this with both global and local registration: https://github.com/tylerkrupicka/vue-json-component

**Comment by lukethompsxn** [comment] 2019-08-18 09:43
If anyone is still having this issue, or has this issue in the future I can confirm that @vxhly fix works!
> ```shell
> import Vue from 'Vue'
> import TreeView from 'vue-json-tree-view'
> Vue.use(TreeView)
> ```
> in your `main.js`

**Closed** 2020-05-20 00:15 UTC
Labels: no-issue-activity

**Comment by vijayrudraraju** [comment] 2020-06-09 19:57
I was getting this issue, turns out I had change the import statement to destructure and grab the TreeView object:
`import { TreeView } from 'vue-json-tree-view';`

**Comment by robmello** [comment] 2021-03-07 15:12
> I was getting this issue, turns out I had change the import statement to destructure and grab the TreeView object:
> `import { TreeView } from 'vue-json-tree-view';`

Thank you Vijay!  +1
